spring:
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acknowledgeOnRecoveryCallback: true
      maxIdleInterval: 60000
      maxAttempts: 3
      concurrency: 3

    defaultTopic: default
    stringTopic: string-topic
    objectTopic: object-topic
    fileUploads: file-uploads

    numPartitions: 3
    fileChunks: file-chunks

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

springdoc:
  version: @springdoc.version@

storage:
  location: "storage"

fileaxe:
  chunkSize: 600000
